os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback

services:
  - docker

install:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - stage: tests
      script:
        - git config --global url."https://github.com/".insteadOf "git@github.com:"
        - cp dist.env .env
        - ./flutter/bin/flutter test
    - stage: build_linux
      if: branch = master
      script:
        - docker run --rm -v $(pwd):/data -w /data saitho/go-flutter hover build linux
        - cd go/build/outputs/linux/ && zip ../linux.zip -r .
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - pnpx semantic-release